CREATE TABLE IF NOT EXISTS `account_shop_plans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_id` VARCHAR(32) NOT NULL,
  `name` VARCHAR(160) NOT NULL,
  `duration_label` VARCHAR(96) NOT NULL,
  `warranty_type` VARCHAR(16) NOT NULL,
  `warranty_days` INT NULL,
  `roboticvn_product_id` VARCHAR(64) NOT NULL,
  `roboticvn_variant_id` VARCHAR(64) NOT NULL,
  `roboticvn_variant_title` VARCHAR(255) NOT NULL,
  `pricing_mode` VARCHAR(16) NOT NULL,
  `fixed_toman` INT NULL,
  `markup_percent` INT NOT NULL DEFAULT 0,
  `custom_fields` JSON NOT NULL,
  `notice_kind` VARCHAR(16) NOT NULL DEFAULT 'none',
  `notice_text` VARCHAR(500) NULL,
  `sort_order` INT NOT NULL DEFAULT 0,
  `is_active` BOOLEAN NOT NULL DEFAULT true,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `account_shop_plans_category_active_sort_idx` (`category_id`, `is_active`, `sort_order`),
  INDEX `account_shop_plans_variant_idx` (`roboticvn_variant_id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
